WITH BY_TYPE AS (
    SELECT CAR.CAR_ID, 
        CAR.CAR_TYPE, 
        CAR.DAILY_FEE, 
        ROUND(CAR.DAILY_FEE * (1 - 0.01 * DISCOUNT.DISCOUNT_RATE) * 30) FEE
    FROM CAR_RENTAL_COMPANY_CAR AS CAR 
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DISCOUNT 
        ON CAR.CAR_TYPE = DISCOUNT.CAR_TYPE
    WHERE CAR.CAR_TYPE IN ("SUV", "세단") AND DISCOUNT.DURATION_TYPE = "30일 이상"
), CANT_BY_DATE AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE < "2022-11-30" AND END_DATE > "2022-11-01"
)

SELECT CAR_ID, CAR_TYPE, FEE
FROM BY_TYPE 
WHERE CAR_ID NOT IN (SELECT * FROM CANT_BY_DATE)
    AND FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
;