WITH F AS (SELECT FOOD_TYPE, MAX(FAVORITES) AS MF
FROM REST_INFO
GROUP BY FOOD_TYPE)

SELECT I.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO AS I LEFT JOIN F ON I.FOOD_TYPE = F.FOOD_TYPE
WHERE I.FAVORITES = F.MF
ORDER BY I.FOOD_TYPE DESC
;