WITH O AS (SELECT ANIMAL_ID, SEX_UPON_OUTCOME
          FROM ANIMAL_OUTS)
SELECT I.ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_INS I JOIN O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE "Intact%" 
    AND (O.SEX_UPON_OUTCOME LIKE "Spayed%" 
         OR O.SEX_UPON_OUTCOME LIKE "Neutered%")
ORDER BY I.ANIMAL_ID
;