WITH A AS (SELECT PRODUCT_ID, SUM(AMOUNT) T_AMOUNT
		  FROM FOOD_ORDER
		  WHERE YEAR(PRODUCE_DATE) = 2022 
		  AND MONTH(PRODUCE_DATE) = 5
		  GROUP BY PRODUCT_ID)
SELECT B.PRODUCT_ID, PRODUCT_NAME, (PRICE * T_AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT B JOIN A ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC