WITH RECURSIVE A(HOUR) AS
(
    SELECT 0
    UNION ALL
    SELECT HOUR +1 FROM A WHERE HOUR < 23
)
SELECT A.HOUR, COALESCE(COUNT(B.ANIMAL_ID), 0) COUNT
FROM A LEFT JOIN ANIMAL_OUTS B ON A.HOUR = HOUR(B.DATETIME)
GROUP BY A.HOUR
ORDER BY A.HOUR
;