WITH A AS (SELECT EMP_NO, AVG(SCORE) A_SCORE, 
		   (CASE 
			   WHEN AVG(SCORE) >= 96 THEN "S"
			   WHEN AVG(SCORE) >= 90 THEN "A"
			   WHEN AVG(SCORE) >= 80 THEN "B"
			   ELSE "C"
			   END) GRADE, 
			(CASE 
				WHEN AVG(SCORE) >= 96 THEN 0.2
				WHEN AVG(SCORE) >= 90 THEN 0.15
				WHEN AVG(SCORE) >= 80 THEN 0.1
				ELSE 0
			END) BONUS_MULT
		  FROM HR_GRADE
          GROUP BY EMP_NO)
SELECT B.EMP_NO, EMP_NAME, GRADE, (SAL * BONUS_MULT) BONUS
FROM A JOIN HR_EMPLOYEES B ON A.EMP_NO = B.EMP_NO
ORDER BY B.EMP_NO