WITH A AS (SELECT MEMBER_ID, COUNT(REVIEW_ID) R_COUNT
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY R_COUNT DESC)

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") REVIEW_DATE
FROM MEMBER_PROFILE AA RIGHT JOIN REST_REVIEW BB
ON AA.MEMBER_ID = BB.MEMBER_ID
WHERE BB.MEMBER_ID IN (SELECT A.MEMBER_ID
                    FROM A
                    WHERE R_COUNT = (SELECT MAX(R_COUNT)
                                    FROM A))
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC
;