SELECT II.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_TREE AS IT JOIN ITEM_INFO AS II ON IT.ITEM_ID = II.ITEM_ID
WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = "RARE")
ORDER BY ITEM_ID DESC
;