WITH T AS (SELECT CAR_ID, CAR_TYPE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = "세단") 
SELECT DISTINCT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H JOIN T ON H.CAR_ID = T.CAR_ID
WHERE MONTH(START_DATE) = 10
ORDER BY H.CAR_ID DESC
;