SELECT ID, FISH_NAME, LENGTH
FROM FISH_NAME_INFO N 
JOIN FISH_INFO I
ON N.FISH_TYPE = I.FISH_TYPE
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LEN
FROM FISH_INFO 
GROUP BY FISH_TYPE) L
ON N.FISH_TYPE = L.FISH_TYPE
WHERE LENGTH = L.LEN
;