WITH EN AS (SELECT DEPT_ID, DEPT_NAME_EN FROM HR_DEPARTMENT)

SELECT EM.DEPT_ID, EN.DEPT_NAME_EN, ROUND(AVG(SAL), 0) AS AVG_SAL 
FROM HR_EMPLOYEES AS EM JOIN EN ON EM.DEPT_ID = EN.DEPT_ID
GROUP BY EM.DEPT_ID
ORDER BY AVG_SAL DESC
;